### ISSUE TITLE
Gradle plugin uploads proguard mapping but the UUID of issues doesn't match

### ISSUE THREAD

**Issue by FilippoVigani** [getsentry/sentry-android-gradle-plugin#415]
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.1

### Proguard

Enabled

### Version

3.2.0 / 3.3.0

### Steps to Reproduce

I'm using Bitrise as a CI/CD tool to build and upload releases to the GPC. In the logs I can see that the proguard mapping file is uploaded to sentry properly. However, when some issues are logged into Sentry the issue `A proguard mapping file was missing` pops up, and I can't see the unsymbolicated stack trace. 

I verified that the UUID does in fact not match, and I can see that in the uploaded app bundle the file `sentry-debug-meta.properties` has the property `io.sentry.ProguardUuids` with a UUID which differs from the UUID of the proguard mapping file uploaded. I can confirm that it matches the "Mapping Uuid" that pops up as an error in the issue on Sentry.

My sentry configuration is the following:
```
sentry {
    includeProguardMapping.set(true)
    includeNativeSources.set(true)
    uploadNativeSymbols.set(true)
    autoUploadProguardMapping.set(true)
    autoUploadNativeSymbols.set(true)
    tracingInstrumentation {
        enabled.set(true)
    }
    ignoredBuildTypes.set(setOf("debug"))
    ignoredFlavors.set(setOf("development"))
}
```

### Expected Result

The uploaded file mapping UUID and the one in the issues should match, and I should be able to see de-obfuscated stack traces.

### Actual Result

These are the relevant logs from the build output (sorry for the [REDACTED] parts, I have a secret env variable that says upload):
```
> Task :app:[REDACTED]SentryProguardMappingsProductionOfficialRelease
  INFO    2022-12-06 15:53:56.568979053 +00:00 Loaded file referenced by SENTRY_PROPERTIES (/bitrise/src/sentry.properties)
> compressing mappings
> [REDACTED]ing mappings
> Uploaded a total of 1 new mapping files
Newly [REDACTED]ed debug symbols:
  2ddfd87f-8657-40ea-a897-3f28357189cd
> Task :app:[REDACTED]CrashlyticsMappingFileProductionOfficialRelease
> Task :app:l8DexDesugarLibProductionOfficialRelease
> Task :app:buildProductionOfficialReleasePreBundle
> Task :app:compileProductionOfficialReleaseArtProfile
> Task :app:packageProductionOfficialReleaseBundle
> Task :app:shrinkBundleProductionOfficialReleaseResources
> Task :app:signProductionOfficialReleaseBundle
> Task :app:produceProductionOfficialReleaseBundleIdeListingFile
> Task :app:createProductionOfficialReleaseBundleListingFileRedirect
> Task :app:bundleProductionOfficialRelease
> Task :app:[REDACTED]SentryNativeSymbolsForProductionOfficialRelease
Execution optimizations have been disabled for task ':app:[REDACTED]SentryNativeSymbolsForProductionOfficialRelease' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/bitrise/src/app/build'. Reason: Task ':app:[REDACTED]SentryNativeSymbolsForProductionOfficialRelease' uses this output of task ':app:createProductionOfficialReleaseBundleListingFileRedirect' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/bitrise/src/app/build'. Reason: Task ':app:[REDACTED]SentryNativeSymbolsForProductionOfficialRelease' uses this output of task ':app:produceProductionOfficialReleaseBundleIdeListingFile' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  INFO    2022-12-06 15:54:26.675105681 +00:00 Loaded file referenced by SENTRY_PROPERTIES (/bitrise/src/sentry.properties)
> Found 20 debug information files
> Resolved source code for 0 debug information files
> Prepared debug information files for [REDACTED]
> Nothing to [REDACTED], all files are on the server
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
BUILD SUCCESSFUL in 5m 44s
88 actionable tasks: 35 executed, 53 up-to-date
```

So the uuid for the uploaded file is `2ddfd87f-8657-40ea-a897-3f28357189cd`, which I can confirm on sentry has been uploaded:
![image](https://user-images.githubusercontent.com/8075379/206031157-d36d6303-c06e-431b-88e7-e64fe5e10d6f.png)

However, here is an issue for this version: 
![image](https://user-images.githubusercontent.com/8075379/206031253-89a8a690-7d89-47fc-8d7f-c86f13f4d2b1.png)

Which is indeed missing from sentry:
![image](https://user-images.githubusercontent.com/8075379/206031376-47af48eb-3495-4f91-952b-14ee5759f561.png)

And I can confirm that's the UUID in the app bundle:
![image](https://user-images.githubusercontent.com/8075379/206031537-afcd7f5e-fb03-4914-8351-9cbd1bfa28c8.png)

Additionally, I tried to build an app bundle in my local machine, and I can verify that the uploaded mappings UUID and the UUID in `sentry-debug-meta.properties` DO match, so the issue only occurs when building through Bitrise.

**Comment by romtsn** [comment]
hmm, that's interesting that it doesn't work on bitrise specifically. Just to confirm - you do not set the proguard-uuid manually (e.g. in the manifest or in code), right?

You also face this with `3.2.0`, correct? Because we did some changes to that in `3.3.0`, but I guess they are not the cause. Can you look for `generateSentryProguardUuidProductionOfficialRelease` task in the logs? This task should be called as many times as `uploadSentryProguardMappings...` task, if not - that would explain the mismatch.

**Comment by FilippoVigani** [comment]
@romtsn I tried with version 3.3.0 and I'm facing the same issue. I do notice that the task is `generateSentryProguardUuidProductionOfficialRelease` is called twice. I should mention that in the same repository two different modules use the sentry plugin (although they are configured to different projects). I don't know if that could be the culprit, as the CD job is configured to deploy only one of the modules (and there are no dependencies from one to the other).

I'm attaching the full log so you can have a look.

[apps_4e216a5b23fe03c8_ca19b9f6-7477-49c8-b8e0-1cfbccf47485-full.txt](https://github.com/getsentry/sentry-android-gradle-plugin/files/10177145/apps_4e216a5b23fe03c8_ca19b9f6-7477-49c8-b8e0-1cfbccf47485-full.txt)

**Comment by FilippoVigani** [comment]
Also you are correct, I do not set the proguard-uuid programmatically (neither in the manifest nor in code)

**Comment by romtsn** [comment]
Ideally it should only be applied to the `:app` module, but from the logs I see that it's called correctly. Do you have multiple `app` modules, or what do you mean by different modules use the plugin?

Also, it looks like one of the tasks from the logs is called for the `testProductionOfficialReleaseUnitTest` task, which shouldn't cause any problems, unless you use the test .apk from this task as a production .apk (which is not the case, I guess?).

I cannot spot the issue from the logs, maybe you could both run the build with `--info` and add `export SENTRY_LOG_LEVEL=debug` to env variables and see if there's something off (or share the logs here)?

**Comment by FilippoVigani** [comment]
I have different android app modules that use the plugin (same repo, different apps).

I tried a new build with the `--info` arg and the `SENTRY_LOG_LEVEL=debug` env variable, but on top of that I removed the workflow step that ran the tests. And it turns out that by removing that, the proguard UUIDs matched.

Here is the full log:

[apps_4e216a5b23fe03c8_30d1def6-01cf-452c-8581-8b1c9e699734-full.txt](https://github.com/getsentry/sentry-android-gradle-plugin/files/10178625/apps_4e216a5b23fe03c8_30d1def6-01cf-452c-8581-8b1c9e699734-full.txt)

Now I think it's important to try and figure out why a unit test step before that causes the UUIDs not to match. If it can help, here is the bitrise yaml configuration that caused the issue:

```
---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
workflows:
  deploy:
    description: Deploys to Google Play (requires setup and $VARIANT, $PACKAGE_NAME
      env variables).
    steps:
    - cache-pull@2: {}
    - change-android-versioncode-and-versionname@1:
        inputs:
        - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"
    - android-lint@0:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
    - android-build@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - module: "$MODULE"
        - build_type: aab
        - variant: "$VARIANT"
    - sign-apk@1:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
    - deploy-to-bitrise-io@2: {}
    - cache-push@2: {}
    - google-play-deploy@3:
        inputs:
        - package_name: "$PACKAGE_NAME"
        - update_priority: '5'
        - service_account_json_key_path: "$BITRISEIO_GOOGLE_PLAY_SERVICE_ACCOUNT_CONFIG_URL"
    envs:
    - RELEASE_SIGNING_STORE_FILEPATH: "/keystores/upload-keystore.jks"
    - RELEASE_SIGNING_STORE_PASSWORD: "$BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
    - RELEASE_SIGNING_KEY_PASSWORD: "$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
    - RELEASE_SIGNING_KEY_ALIAS: "$BITRISEIO_ANDROID_KEYSTORE_ALIAS"
  deploy_official:
    description: Deploys TrueScreen to Google Play
    before_run:
    - setup
    - set_official_env
    - deploy
  set_official_env:
    description: Set TrueScreen envs for deploy
    steps:
    - set-env-var@0:
        inputs:
        - destination_keys: VARIANT
        - value: productionOfficialRelease
    - set-env-var@0:
        inputs:
        - destination_keys: PACKAGE_NAME
        - value: com.truescreen.app
  setup:
    description: Sets up repo and files.
    steps:
    - activate-ssh-key@4: {}
    - git-clone@6: {}
    - cache-pull@2: {}
    - file-downloader@1:
        inputs:
        - destination: "$GOOGLE_SERVICES_PATH"
        - source: "$BITRISEIO_GOOGLE_SERVICES_URL"
    - file-downloader@1:
        inputs:
        - destination: "$RELEASE_SIGNING_STORE_FILEPATH"
        - source: "$BITRISEIO_ANDROID_KEYSTORE_URL"
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    envs:
    - RELEASE_SIGNING_STORE_FILEPATH: "/keystores/upload-keystore.jks"
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: standard
app:
  envs:
  - opts:
      is_expand: false
    PROJECT_LOCATION: "."
  - opts:
      is_expand: false
    MODULE: app
  - opts:
      is_expand: false
    GOOGLE_SERVICES_PATH: app/src/production/google-services.json
trigger_map:
- push_branch: main
  workflow: deploy_official
```
And this is the updated one, where the uploaded UUID and the UUID embedded in the app bundle match
```
---
    format_version: '11'
    default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
    project_type: android
    workflows:
      deploy:
        description: Deploys to Google Play (requires setup and $VARIANT, $PACKAGE_NAME
          env variables).
        steps:
        - cache-pull@2: {}
        - change-android-versioncode-and-versionname@1:
            inputs:
            - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"
        - android-lint@0:
            inputs:
            - project_location: "$PROJECT_LOCATION"
            - variant: "$VARIANT"
        - android-build@1:
            inputs:
            - project_location: "$PROJECT_LOCATION"
            - module: "$MODULE"
            - build_type: aab
            - arguments: "--info"
            - variant: "$VARIANT"
        - sign-apk@1:
            run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
        - deploy-to-bitrise-io@2: {}
        - cache-push@2: {}
        - google-play-deploy@3:
            inputs:
            - package_name: "$PACKAGE_NAME"
            - update_priority: '5'
            - service_account_json_key_path: "$BITRISEIO_GOOGLE_PLAY_SERVICE_ACCOUNT_CONFIG_URL"
        envs:
        - RELEASE_SIGNING_STORE_FILEPATH: "/keystores/upload-keystore.jks"
        - RELEASE_SIGNING_STORE_PASSWORD: "$BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
        - RELEASE_SIGNING_KEY_PASSWORD: "$BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
        - RELEASE_SIGNING_KEY_ALIAS: "$BITRISEIO_ANDROID_KEYSTORE_ALIAS"
      deploy_official:
        description: Deploys TrueScreen to Google Play
        before_run:
        - setup
        - set_official_env
        - deploy
      set_official_env:
        description: Set TrueScreen envs for deploy
        steps:
        - set-env-var@0:
            inputs:
            - destination_keys: VARIANT
            - value: productionOfficialRelease
        - set-env-var@0:
            inputs:
            - destination_keys: PACKAGE_NAME
            - value: com.truescreen.app
      setup:
        description: Sets up repo and files.
        steps:
        - activate-ssh-key@4: {}
        - git-clone@6: {}
        - cache-pull@2: {}
        - file-downloader@1:
            inputs:
            - destination: "$GOOGLE_SERVICES_PATH"
            - source: "$BITRISEIO_GOOGLE_SERVICES_URL"
        - file-downloader@1:
            inputs:
            - destination: "$RELEASE_SIGNING_STORE_FILEPATH"
            - source: "$BITRISEIO_ANDROID_KEYSTORE_URL"
        - install-missing-android-tools@3:
            inputs:
            - gradlew_path: "$PROJECT_LOCATION/gradlew"
        envs:
        - RELEASE_SIGNING_STORE_FILEPATH: "/keystores/upload-keystore.jks"
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: standard
    app:
      envs:
      - opts:
          is_expand: false
        PROJECT_LOCATION: "."
      - opts:
          is_expand: false
        MODULE: app
      - opts:
          is_expand: false
        GOOGLE_SERVICES_PATH: app/src/production/google-services.json
      - opts:
          is_expand: false
        SENTRY_LOG_LEVEL: debug
    trigger_map:
    - push_branch: main
      workflow: deploy_official
    
```
